[package]
name = "tkb-wasm"
authors = ["Shane OHanlon <sohanlon07@gmail.com>"]
description = "My first Wasm app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
spin-sdk = "3.0.1"

[workspace]
