spin_manifest_version = 2

[application]
name = "tkb-wasm"
version = "0.1.0"
authors = ["Shane OHanlon <sohanlon07@gmail.com>"]
description = "My first Wasm app"

[[trigger.http]]
route = "/tkb"
component = "tkb-wasm"

[component.tkb-wasm]
source = "tkb_wasm.wasm"
allowed_outbound_hosts = []
[component.tkb-wasm.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
